### ISSUE TITLE
Change the way issues and pull requests sync from GitHub

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#1097]
# Problem

Right now, both issues and pull requests that we receive from the GitHub API sync directly to `CodeCorps.Task` records. We need to modify this so that:

- A pull request only syncs to `GithubPullRequest`
- An issue syncs to `GithubIssue`, `Task`, and kicks off a sync to `GithubPullRequest`

When the issue is syncing to `GithubPullRequest`, we'll need to use the `pull_request` `url` in the issue payload body to fetch the pull request data from the GitHub API. This data can then be used in the `GithubPullRequest`.

This means that `Sync.PullRequest.Task` will go away entirely.

**Comment by joshsmith** [comment]
- issue payload
  - contains pull request
    - fetch pull request
    - sync issue with pull request payload
  - is issue
    - sync issue only
- pull request payload
  - fetch issue
  - sync issue with pull request payload

**Comment by joshsmith** [comment]
We actually get the following event payload types from webhooks:

- `Issue`: (this never receives issue events for pull requests)
  - issue only - `%{"issue" => _}`
    - sync
      - issue
- `IssueComment`: (can be for either issues or pull requests)
  - issue only - `%{"issue" => _, "comment" => _}`
    - sync
      - issue
      - comment
  - issue w/ pull request - `%{"issue" => %{"pull_request" => %{"url" => _}}, "comment" => _}}`
    - fetch
      - pull request
    - sync
      - issue
      - pull request
      - comment
- `PullRequest`: (only for pull requests, but doesn't give us enough info for the issue since the `Issue` webhook only receives issue events)
  - issue w/ pull request - `%{"pull_request" => %{"issue_url" => _}}`
    - fetch
      - issue
    - sync
      - issue
      - pull request

**Comment by joshsmith** [comment]
Requests to the v3 API can return the following payloads:

- `Issue`: (unlike `Issue` events, can return either issues or pull requests)
  - issue only - `%{}`
    - sync
      - issue
  - issue w/ pull request - `%{"pull_request" => %{"url" => _}}`
    - fetch
      - pull request
    - sync
      - issue
      - pull request
- `Comment`: (can be for either issues or pull requests, but not enough detail to know)
  - unknown - `%{"issue_url" => _}`
    - fetch
      - issue
      - maybe pull request
    - sync
      - issue
      - maybe pull request
      - comment
- `PullRequest`: (only for pull requests)
  - issue w/ pull request - `%{"issue_url" => _}`
    - fetch
      - issue
    - sync
      - issue
      - pull request

**Comment by begedin** [comment]
This sounds about right, but there may be a step we can use to save up on some requests.

The way I see it, once we have a github record stored, we don't have to assume it's changed and refetch it. If it did change, we'll get a webhook for that change explicitly.

That actually means, with the example of an issue comment for a pull request

- match issue, sync if unmatched
- match pull request, fetch and sync if unmatched
- sync comment

If a pull request is matched against a stored record, we don't need to explicitly fetch the latest data. Presumably, we will receive it anyway, through a pull request webhook.

I get the argument - it may be safer to fetch anyway, but I sort of feel like that in fact may cause more trouble, because we'll have a bunch of duplicate operation happening 
- we'll be fetching and updating the pull request manually
- we'll be updating the pull request due to handling a related webhook

IssueComment created/updated means the change was on the issue comment, not the issue or the pull request.

That being said, if implemented correctly, and it turns out it actually is safer to fetch and update the pull request even though we already matched it, then that's a different thing altogether.

However, the way I see it

- we got the comment created event
- we can match the issue from it directly. it really should be there we would've gotten an "issue created" already
- if it's a pull request that issue should already have a pull request attached, because we got a "pull request created" event before that comment was ever created/updated
- if that pull request changed, we also got the "pull request updated event"

- it looks like the only spot where we may have to fetch is the pull request webhook, since there's no issue payload. I was hoping the PR payload has enough information, but these are my findings:

- `:body` - present 
- `:closed_at` - present
- `:comments_url` - present
- `:events_url` - missing
- `:github_created_at` - present
- `:github_id` - present
- `:github_updated_at` - present
- `:html_url` - present
- `:labels_url` - missing
- `:locked` - present
- `:number` - present
- `:state` - present
- `:title` - present
- `:url` - present, but that's the PR url, we would need to map from `issue_url`, which is also present

So we're missing `labels_url` and `events_url`, and I'm not 100% sure if other fields match up correctly, meaning this is a place where we would have to fetch.
