### ISSUE TITLE
Identify differences in Postgres db's between Rails and Phoenix and plan migration

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#159]
If someone can identify differences we need to account for between these two databases that we need to address in our `phoenix.sql`'s schema, then we can start creating tasks for adding migrations to handle those. These could be column differences, table name differences, etc

Some things exist in Phoenix that are Ecto defaults that we may want to keep.

We should especially identify index name differences, along with anything else you notice.

We should also sketch a rough plan for how we should handle porting data over and any gotchas we might encounter in doing so.

You can see schema dumps here: https://gist.github.com/JoshSmith/afc532487fe6e63fb8bf6dd64e393bcb

Known differences:
- `inserted_at` is `created_at` on rails on every table
- ignore tables `comment_images`, `comment_user_mentions`, `github_repositories`, `import*`, `notifications`, `oauth*`, `post_images`, `post_likes`, `post_user_mentions`, `preview_user_mentions`
- ignore `schema_migrations` since those are different for Rails and Phoenix

**Comment by eriksandall** [comment]
phoenix.sql `CREATE TABLE categories` specifies character length for the `name`, `slug`, and `description` columns but rails.sql does not. 

Is that too granular of a detail, or should I call these out too?

**Comment by eriksandall** [comment]
- phoenix has `assign_number()` FUNCTION that is not in rails
- TABLE `ar_internal_metadata` is missing from phoenix
- TABLE `roll_skills` is missing in rails
- `categories` table has column 'description character varying(255)' in phoenix but 'description text' in rails
- all ALTER TABLE (but not ALTER TABLE ONLY) in rails precedes the table with `public.` (e.g. `public.ar_internal_metadata`) but not in phoenix. Maybe not an issue since `search_path` is set to `public` earlier in the script?
- all `ALTER TABLE ... OWNER TO postgres' in phoenix, but`ALTER TABLE ... OWNER TO joshsmith' in rails

**`comments` TABLE:**
- `body` and `markdown` columns are NOT NULL in phoenix but not in rails
- `user_id` and `post_id` columns are NOT NULL in rails but not in phoenix
- `aasm_state` column exists in rails but not in phoenix

**`organization_memberships` TABLE:**
- `role` column is missing the default value specification
- `member_id` and `organization_id` columns NOT NULL in phoenix but not in rails

**`organizations` TABLE:**
- `name` and `slug` columns are NOT NULL rails but not in phoenix
- `icon_file_name`, `icon_content_type`, `icon_file_size`, `icon_updated_at`, and `base64_icon_data` columns are missing in phoenix
- `icon` column exists in phoenix but not in rails
- `description` column is type character and varying in phoenix but text in rails

**`posts` TABLE:**
- `status`, `post_type`, `title`, `body`, and `number` columns are NOT NULL in phoenix but not rails
- `aasm_state' and`comments_count` columns exist in rails but not phoenix
- `state` column exists in phoenix but not in rails
- `body character varying(255)` in phoenix versus `body text` in rails
- `markdown character varying(255)` in phoenix versus `markdown text` in rails
- the table is named `preview` in phoenix but `previews` in rails
- in the `project_categories` table, the `project_id` and `category_id` columns are NOT NULL in phoenix but not rails
- `project_roles` table is missing from phoenix

**`projects` TABLE:**
- `icon_file_name`, `icon_file_size`, `icon_content_type`, `icon_updated_at`, `base64_icon` columns missing in phoenix
- `icon_*_url` columns exist in phoenix but not in rails
- `organization_id` column is NOT NULL in rails but not in phoenix
- `long_description_*` columns are of type character varying(255) in phoenix, but text in rails

**Comment by eriksandall** [comment]
Need to verify:
- all `body` columns are c_haracter varying(255)_ in phoenix versus _text_ in rails

**Comment by eriksandall** [comment]
- `role_skills` table is missing `cat` column in phoenix.
- `schema_migrations` table has `inserted_at` column in phoenix but not in rails
- `skills` table has `slug` column in rails but not phoenix

**`slugged_routes` TABLE:**
- `organization_id` and `user_id` columns exist in phoenix but not in rails
- `owner_id` and `owner_type` columns exist in rails but not in phoenix
- `slug` column is NOT NULL in rails but not in phoenix
- `user_relationships` table is missing from phoenix

**`users` TABLE:**
- `encrypted_password` is NOT NULL in rails but not in phoenix
- `confirmation_token`, `remember_token`, `facebook_*`, `base64_photo`, `photo_*`, `aasm_state` and `theme` are missing in phoenix
- `username` is NOT NULL in phoenix but not in rails
- `website`, `biography`, `first_name`, and `last_name` are of type character varying in phoenix but of type text in rails
- `photo` exists in phoenix but not in rails

**Comment by eriksandall** [comment]
- `comments_post_id_index` and `comments_user_id_index` are in phoenix but not in rails
- `index_categories_on_slug` index is created `USING btree (lower((slug)::text))` in phoenix versus `USING btree (slug)` in rails

**Indexes existing in phoenix but not rails:**
- `index_projects_on_user_id_skill_id`
- `posts_number_project_id_index`
- `posts_project_id_index`
- `posts_user_id_index`
- `project_skills_project_id_index`
- `project_skills_skill_id_index`
- `project_skills_skill_id_index`
- `user_roles_user_id_role_id_index`
- `users_lower_username_index`

**Indexes existing in rails but not phoenix:**
- `index_previews_on_user_id`
- `index_project_roles_on_project_id_and_role_id`
- `index_projects_on_organization_id`
- `index_slugged_routes_on_owner_id_and_owner_type`
- `index_user_relationships_on_follower_id`
- `index_user_relationships_on_following_id`
- `index_users_on_remember_token`
- TRIGGER `post_created` exists in phoenix but not in rails

**Comment by eriksandall** [comment]
**INDEX name differences:**
- `index_skills_on_title` in phoenix versus `index_skills_on_slug` in rails [OK, since no `slug` column in the phoenix table?]
- `organization_memberships_member_id_organization_id_index` in phoenix versus `index_organization_memberships_on_member_id_and_organization_id` in rails
- `organizations_lower_slug_index` in phoenix versus `index_organizations_on_slug` in rails [the phoenix index is created `USING btree (lower((slug)::text))` while rails is `USING btree (slug)`]
- `project_categories_project_id_category_id_index` in phoenix versus `index_project_categories_on_project_id_and_category_id` in rails
- `project_skills_project_id_skill_id_index` in phoenix versus `index_project_skills_on_project_id_and_skill_id` in rails
- `project_skills_project_id_skill_id_index` in phoenix versus `index_project_skills_on_project_id_and_skill_id` in rails
- `slugged_routes_lower_slug_index` in phoenix versus `index_slugged_routes_on_slug` in rails
- `user_categories_user_id_category_id_index` in phoenix versus `index_user_categories_on_user_id_and_category_id` in rails
- `users_email_index` in phoenix versus `index_users_on_email` in rails

**Comment by eriksandall** [comment]
**FOREIGN KEY constraints have different names for these TABLES:**
- `comments` 
- `user_categories`
- `project_skills`
- `preview`
- `posts`
- `projects`
- `preview` (`previews` in rails)
- `project_categories`

**FOREIGN KEY constraints exist in phoenix but missing in rails for these TABLES:**
- `organization_memberships`
- `slugged_routes`
- `user_roles`
- `user_skills`

**Comment by joshsmith** [comment]
I think this is basically good to go now. Closing now that I've updated my SQL migration file enough. Thanks @eriksandall.
