### ISSUE TITLE
Do list and detail endpoints need same data?

### ISSUE THREAD

**Issue by snewcomer** [code-corps/code-corps-api#184]
Noticed that no matter if list or show endpoint, it returns the same set of fields.  If the list endpoint needs only a subset of the data, then should we re-configure the view?

**Comment by joshsmith** [comment]
@snewcomer can you clarify? I think this is how JSON API is intended to work.  Variation between the attributes on requests would be problematic.

**Comment by snewcomer** [comment]
@JoshSmith I did not know that!  Guess I was just referring to that in many cases, the data needed to populate a list vs a detail can be quite different.  Especially on a grid w/ 50 items, those unneeded queries (esp for related data that isn't used to populate the grid for example) can lead to quite lg performance issues.  But if JSON API enforces same attributes/relationships for all requests, then thats just how it has to be!

**Comment by snewcomer** [comment]
I guess I would imagine JSON API wouldn't be that strict given detail vs. list payload could be quite different.

**Comment by joshsmith** [comment]
@snewcomer when it's referencing a relationship the attributes of the referenced objects usually are not included.

When you're just rendering an index of users, for example, the queries won't be all that large. If a user has several `has_many` relationships, then you're just doing that many relationships x `IN` clauses in SQL. There won't be `n+1` queries and the performance won't really suffer.

In Phoenix a request to this `index` endpoint with ~40 users and LOTS of relationships takes 24ms. With pagination added in, this is not bad at all.

**Comment by joshsmith** [comment]
There's definitely reason to consider in some edge cases – where the performance really _is_ suffering – breaking out your endpoints to render different views depending on the situation. I've done this before in Rails where the performance was particularly bad due to some really poor architecture on my part (trying to monkey-patch around things I wanted in Ember but couldn't have easily). But I wouldn't suggest it as the default since you can see that the response time, even for lots of results and 10+ queries, is not bad.

**Comment by joshsmith** [comment]
With Ember as your client and using `ember-data`, you'd especially want to consider what side effects this might have in your app, as the statefulness of `ember-data` could lead to some funky data mismatch edge cases.

**Comment by snewcomer** [comment]
got it.  More headaches than benefits :)
