### ISSUE TITLE
Determine if tasks/:task_id/comments/:id is necessary

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#340]
We have a `/tasks/:task_id/comments/:id` that our Ember app does not appear to be hitting in tests (is not in the Mirage config), but which the API does serve.

We should determine if this route is strictly necessary, and if not, remove it.

**Comment by begedin** [comment]
See my reply on https://github.com/code-corps/code-corps-api/issues/341#issuecomment-252615504

The same applies here.

**Comment by begedin** [comment]
I took another look at this and our ember app, within the `project/tasks/task` route actually does explicitly fetch comments using a `taskId` query.

However, the only route the ember app needs is `tasks/:task_id/comments`. The `tasks/:task_id/comments/:id` is completely unnecessary and would be to begin with, since the `:id` is more than enough to identify a comment (It's an actual id, not a number).

**Comment by begedin** [comment]
Just to add some info to this issue, so there's no confusion in the future, pr #372 removed both `tasks/:task_id/comments` and `tasks/:task_id/comments/:id` routes. 

`tasks/:task_id/comments/:id` was unnecessary, so it has been removed completely.

`tasks/:task_id/comments` has been replaced with `/comments/`, which allows fetching multiple comments using a coalesced id filter, in line with our other endpoints.
