### ISSUE TITLE
Determine if organizations/:organization_id/memberships is necessary

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#341]
We have a `/organizations/:organization_id/memberships` that our Ember app does not appear to be hitting in tests (is not in the Mirage config), but which the API does serve.

We should determine if this route is strictly necessary, and if not, remove it.

**Comment by begedin** [comment]
Looked into this:

First of all, ember fetches memberships using ID coalescing, so technically, we do not need this endpoint, nor do we need an `organization_filter` on the `OrganizationMembership.index_filters`.

That means that when we fetch an organization, it will contain a list of membership ids. Later, when needed, those will be fetched via coalesced IDs, same as any other `hasMany` relationship.

Second, I was confused as to how this even works at all, since there's only one index action in the membership controller and both `:org_id/membership` and `org_memberships/`target it.

Turns out, `some_organization_id/memberships` and `organization_memberships?organization_id=some_organization_id` is functionally equivalent. The dynamic route part get's mapped as `organization_id` and merged into the `params` map.

To explain by example, we had the following test 

``` Elixir
test "lists all resources for specified organization", %{conn: conn} do
  organization = insert(:organization)
  [membership_1, membership_2] = insert_pair(:organization_membership, organization: organization)
  insert(:organization_membership)

  path = conn |> organization_organization_membership_path(:index, organization)
  response = conn |> get(path) |> json_response(200)

  assert ids_from_response(response) == [membership_1.id, membership_2.id]
end
```

To that one, I added the following test:

``` Elixir
test "lists all resources for specified organization by standard path", %{conn: conn} do
  organization = insert(:organization)
  [membership_1, membership_2] = insert_pair(:organization_membership, organization: organization)
  insert(:organization_membership)

  path = conn |> organization_membership_path(:index, %{organization_id: organization.id})
  response = conn |> get(path) |> json_response(200)

  assert ids_from_response(response) == [membership_1.id, membership_2.id]
end
```

They both work just fine. The difference is just the path.

The conclusion would be, yes, we should be able to safely remove the `GET /:org_id/memberships`. We should, however, also be able to remove the `organization_filter` from `CodeCorps.OrganizationMembership.index_filters` as well as  from `CodeCorps.ModelHelpers` if that's the only place it's used in.

**Comment by joshsmith** [comment]
@begedin should this still be open?

**Comment by begedin** [comment]
It should not. Not sure why It didn't close.
