### ISSUE TITLE
Consider security implications of rendering 404 versus 401 or 403 error

### ISSUE THREAD

**Issue by amyschools** [code-corps/code-corps-api#392]
See comment from @JoshSmith on pull request #386 

Security implications of returning a 401 or 403 vs just a 404 to say that the object doesn't exist, so people don't sneak around trying to find extra information about cards in our API somehow.

**Comment by joshsmith** [comment]
In order to do this, we need to think through whether we perceive there being significant benefit in using a 404 over a 401 or 403, and where we might want those to apply (e.g. sensitive data or PII).

The downside to a 404 is that it's less verbose and therefore error handling would be harder, as would debugging for a developer.
