### ISSUE TITLE
Set current donation goal appropriately

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#479]
# Problem

We need to set the proper donation goal to `current` when:

- the donation goals are updated
- the cached total donated column changes on the project

We'll need to find the donation goal that is most closely above the current amount and set that to the current goal. That is, the goal can shift depending on the other goals and the current monthly raised.

The other goals will need to be set to `current: false` in that case.

**Comment by joshsmith** [comment]
There is a `Repo.aggregate` fn that will help here for creating the cache in the first place. Can be created across a Project's active Subscription amounts.

**Comment by begedin** [comment]
If I'm understanding this correctly, the user is not the one setting the current goal? It's done automatically?

How would we handle having enough donations to fulfill the current goal and work towards the next one?

We need to think this through a bit, I feel.

Just some basic thinking from my side:

If it's done automatically, we get the total donated towards project, then subtract donation goals in the order from lowest amount needed to highest, until we get above the amount donated. The first that got above is the current goal. The goals subtracted are fulfilled. The goals not yet subtracted are "future goals". We could have some sort of virtual field, or a custom view attribute that determines these things.

If it's marked by the user, then the "fulfilled" status would likely have to be non-virtual. We also need a pretty decent UI to get that working right. Among other things, the UI would have to "force the user" to mark a goal as current and mark enough goals as fulfilled, so that the remainder is less than the current goal's required amount.

Overall, an additional complication happens when something changes with subscriptions. We would have to somehow update the goals in that case. It would definitely be simpler to handle if all of it is done   automatically, though. Still, even if done manually, it's doable. The system would have to detect a change  and notify the user that their goals need fixing.

**Comment by begedin** [comment]
Additional note. 

I might be completely misunderstanding this. Maybe the goals are more like kickstarter goals, where each goal sort of includes the previous one? In that case, all of this is way simpler to deal with and an automatic system definitely makes way more sense.
