### ISSUE TITLE
Check if the account is ready to start taking payments before a plan can be created

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#511]
# Problem

We want to be able to check that an account is actually ready to start taking payments before a plan can be created.

There is some flag on Stripe accounts that lets you know whether Stripe has actually approved them to begin taking payments.

We should modify the UI to actually prevent the user from creating any sort of donation goal or anything until this is resolved, and have a refresh button or something with some helper text.

https://projects.invisionapp.com/share/RT8PS9FK2#/screens/191325319

I think "verification" is the wrong word there and we actually mean "approve." We should also let them know if Stripe denied their account for some reason.

We'll need to update this through webhooks. Not sure which event.

**Comment by begedin** [comment]
I looked into this and if I'm understanding it correctly, the field we're looking for is `charges_enabled`, as well as, possibly, `transfers_enabled` (though we should probably look at that separately.

From https://stripe.com/docs/api#account_object-charges_enabled
>`charges_enabled, boolean`

> Whether or not the account can create live charges

From https://stripe.com/docs/api#account_object-transfers_enabled


>`transfers_enabled, boolean`

>Whether or not Stripe will send automatic transfers for this account. 
This is only false when Stripe is waiting for additional 
information from the account holder.

And also https://stripe.com/docs/api#account_object-verification

>verification, MANAGED ACCOUNTS ONLY, hash

>The state of the account’s information requests, including what information is needed and by when it must be provided.

The way I understand it, if an account can charge a user, `charges_enabled` will be set to true. If it can also transfer funds from stripe to their external account, `transfers_enabled` will be set to true. If either is `false`, the `verification` hash will be populated with additional information for managed accounts only. 

We are rendering both `charges_enabled` and `transfers_enabled` in our view, so that part is not a  problem. The "refresh" button would simply trigger a `stripeConnectAccount.reload()`.

As for the correct webhook, the only one I can think of is `account.updated`, which we are already handling, so that should be fine as well.

Considering that, it ought to be enough to, on the client, add the button and prevent making a plan until `charges_enabled` is `true`. I think `transfers_enabled` could be false initially, but we may want to give the user a warning if it is false, so that they are aware they need to do something to be able to transfer funds from stripe to their own account.

**Comment by begedin** [comment]
The thing that did need changing on the API side of things was to additionally check the `charges_enabled` flag before creating a plan, which I did in #514

**Comment by begedin** [comment]
The API part for this is done, closing. 

The Ember part is defined in code-corps/code-corps-ember#816
