### ISSUE TITLE
Report errors from Stripe to Sentry

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#540]
# Problem

Right now it looks like our errors on Stripe are being swallowed and not reported to Sentry. We need to ensure that the controller does render out the proper response but also sends the right error up to Sentry so that we can track these errors.

**Comment by begedin** [comment]
I looked into this.

`stripity-stripe` is not raising exceptions, so automatic error capture provided by `sentry-elixir` cannot work. We can, however, make it so that exceptions will be raised, or make use of `Sentry.send_event`.

What I think the proper first step should be, though, is to remove all of those `handle_create_result`
methods which render a 500 explicitly. Those are basically swallowing errors which should be logged otherwise and are not useful to our client at all, since they provide no information on what went wrong. Instead, the client is inferring what went wrong based on the step in which a server got an internal server error.
