### ISSUE TITLE
Add StripeConnectAccountController update for setting external account

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#572]
# Problem

We want to add an `update` on `StripeConnectAccountController` to allow for setting `external_account` to a bank account token string.

We likely want to listen for the bank account being created inside a webhook rather than trying to deal with it in one go, to reduce complexity. Can be a separate task.

**Comment by joshsmith** [comment]
@begedin are we expanding this into more of an `update` to handle the other fields from Ember and render out other data that Ember is expecting?

**Comment by begedin** [comment]
For now, I think the simpler and quicker approach is to have the following methods in stripe account service:

* `add_external_account` - uses Stripe API to set an external account field
* `add_verification_document` - uses Stripe API to set a verification document field
* `update_funds_recipient` - uses Stripe API to update all of the funds recipient information

Once we have those three done (since they are separate PRs and issues), the whole thing should work and then we can invest a hopefully minor amount of time to merge it into one.

**Comment by joshsmith** [comment]
@begedin did you want to open separate issues for those?

**Comment by begedin** [comment]
@JoshSmith Renamed this one and created #586
