### ISSUE TITLE
Elixir.KeyError: key :id not found in: %{available: [%{amount: 0, currency: "usd", source_types: %{card: 0}}], con...

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#689]
https://sentry.io/code-corps/code-corps-api/issues/216463221/

```
Elixir.KeyError: key :id not found in: %{available: [%{amount: 0, currency: "usd", source_types: %{card: 0}}], connect_reserved: [%{amount: 0, currency: "usd"}], livemode: true, object: "balance", pending: [%{amount: 0, currency: "usd", source_types: %{card: 0}}]}
  File "lib/code_corps/stripe_service/adapters/stripe_event.ex", line 54, in CodeCorps.StripeService.Adapters.StripeEventAdapter.add_object_id/2
  File "lib/code_corps/stripe_service/adapters/stripe_event.ex", line 24, in CodeCorps.StripeService.Adapters.StripeEventAdapter.to_params/2
  File "lib/code_corps/stripe_service/webhook_processing/event_handler.ex", line 38, in CodeCorps.StripeService.WebhookProcessing.EventHandler.create_event/3
  File "lib/code_corps/stripe_service/webhook_processing/event_handler.ex", line 10, in CodeCorps.StripeService.WebhookProcessing.EventHandler.handle/3
  File "lib/task/supervised.ex", line 85, in Task.Supervised.do_apply/2
...
(1 additional frame(s) were not displayed)

(KeyError) key :id not found in: %{available: [%{amount: 0, currency: "usd", source_types: %{card: 0}}], connect_reserved: [%{amount: 0, currency: "usd"}], livemode: true, object: "balance", pending: [%{amount: 0, currency: "usd", source_types: %{card: 0}}]}
```

**Comment by begedin** [comment]
Hm.

The issue is simple. The object within our event data has an "object" value of balance, but no "id" value.

Since we access these through `event.data.object.object` and  `event.data.object.id` respectively, instead of through `Map.get`, a `KeyError` is raised.

The fix is simple - use nesting instead. 

This, however, opens a whole other potential issue.

Based on https://stripe.com/docs/api#balance_object

The balance object does not have an id. It's implicitly tied to the account it's retrieved from. Lucky for us, that means that, with both a connect and a platform event, we do have all the information required to store it now and potentially handle it later and when this issue is fixed, we will have done so, but I could still use another pair of eyes to confirm that is the case. What I'm saying is:

* For a `balance.available` event on the platform endpoint, we have our own platform account id, so when we later want to handle such an event, we can use that.
* For the same event on the connect account, we will store the `user_id` (which is the connected account id) as part of the event storing for later handling. `user_id` will be the connect account, `object_type` will be `"balance"` and `object_id` will be `nil`. With the first two, we will be able to retrieve the current balance for the account.

Does that sound right? Is a fix of simply fetching object id while allowing nils enough?

**Comment by joshsmith** [comment]
This sounds right to me.
