### ISSUE TITLE
Add states and transitions for donations onboarding

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#706]
# Problem

We need to rewrite the `Transition.UserState` module to allow for some flexibility with signing up from the donations page:

- `signed_up` becomes `signed_up_normally`
- Move `apply_state_transition` to the regular changeset
- Add `signed_up_donating`
- Add `donated`
- Allow for a state to be set with `sign_up_normally`, `sign_up_donating`, and `donate`
- Can transition from `signed_up_donating` to `donated`
- Possibly add a relationship to the project they're donating to when signing up
- Can transition from `donated` to `edited_profile` via `edit_profile`

**Comment by begedin** [comment]
I went in a slightly different direction with this. 

The problem is, there is no `signed_up` `state_transition`. There is the `signed_up` `state`, which is the user model default. With that in mind, it's much easier to simply allow for initial setting of `state` to something like `signed_up_donating` instead of falling back to default.

The advantages of this are

- there is no need to migrate existing data
- the normal flow is `signed_up -> edited_profile -> selected_categories -> selected_roles -> selected_skills`
- the alternative path differs just in that it replaces the `signed_up` step with `signed_up_donating -> donated`

**Comment by joshsmith** [comment]
This has been implemented, though not precisely as described above. See #776
