### ISSUE TITLE
Track reasons for GitHub event errors in database

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#873]
# Problem

For the `milestoned` action, which I don't believe is currently handled, our issue events result in an `errored` status. Although the returned error in Elixir may have `:not_fully_implemented`, this does not appear to be recorded in the database.

**Comment by begedin** [comment]
We don't really have a concept of milestones on our side, so I'm not sure what ought to be done here? Do we record an event with a special status and return an ok response, instead of erroring it out?

Maybe something like, `processed_noop`?

Do we just mark it as `processed` and be done with it?

The way I see it, we wont be going through old events once we support them anyway, since github doesn't work like that. 

Presumably, if we start supporting a new github feature in the future, we will instead go through applicable records and do a manual background sync.

With that in mind, it may even make sense to mark the event as unsupported and be done with it.

**Comment by joshsmith** [comment]
Yeah I think marking it as unsupported is really what we want. What I meant is that we get specific with why something "errored" in elixir itself but not in what we record to the database. For other errors we should also really keep track of the reason.
