### ISSUE TITLE
Timestamps on issues/comments do not match GitHub's

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#878]
# Problem

When an issue is synced from GitHub, the `inserted_at` timestamp is used as the timestamp in the UI for when the task was created/written. This is not correct and can lead to some confusing differences between GitHub's timestamps and our own.

We should correct this by specifying the timestamp when the sync happens, using the data returned by GitHub's payload.

@begedin question for you is whether we should consider adding a different timestamp here to distinguish between `inserted_at` (which has a very particular meaning) and when the issue was _actually_ posted at.

**Comment by begedin** [comment]
@JoshSmith I did not consider that, but yes, it would make sense to keep "inserted_at" as the timestamp for then the record was created in our own database.

As for tracking `posted_at` in relation to github, I'm thinking we either

1. Leave it for now - we don't have an actual use yet, other than UI
2. Name it `inserted_on_github_at` (To keep ecto conventions). If we're storing it just for the sake of it, then an `edited_on_github_at` makes sense to.

I'd actually vote on leaving it be right now. When we find we have a use for it, we can easily add it in.  Sure, we'd then have to use a script to update those fields across our tasks, but that's not difficult to do.

**Comment by joshsmith** [comment]
I raised the issue exactly because it's confusing in the UI right now. I'd like to see a `post_created_at` and `post_edited_at` (and `comment_` versions, too) for these that takes the time from either us or GitHub depending on source. The UI would then use the `post_` and `comment_` for timestamp display instead of the default as it currently does.

**Comment by begedin** [comment]
This would then involve

## For comments - #887

- add `comment_created_at`, `comment_updated_at` timestamp fields
- modify `CodeCorps.Comment.create_changeset/2` to update `comment_created_at` to the current timestamp
- add `CodeCorps.Comment.update_changeset/2`, which calls `changeset/2` and additionally sets the value of `comment_updated_at` to the current timestamp
- modify `CodeCorpsWeb.CommentController.update/2` so it calls `Comment.update_changeset/2` instead of `Comment.changeset/2`
- probably make `Comment.changeset/2` private, if no other piece of the code is using it
- modify `Comment.changeset/2` tests so they are actually `Comment.update_changeset/2` tests and add an assertion for the `comment_updated_at` field being set, **if the changeset was made private**
- if the changeset **was not made private**, add `Comment.update_changeset/2` tests in addition to the existing tests
- modify `Comment.create_changeset/2` tests by adding an assertion for the `comment_created_at` field

- **this is a good merge point**. The rest can be done separately

- modify `CodeCorps.GitHub.Event.IssueComment.ChangesetBuilder.build_changeset/3` to set both `comment_updated_at` and `comment_inserted_at` fields to their equivalent values in the github  payload
- add test assertions for `build_changeset/3` verifying that this is the case.

## For tasks - #888

- add `task_created_at`, `task_updated_at` timestamp fields
- modify `CodeCorps.Task.create_changeset/2` to update `task_created_at` to the current timestamp
- add `CodeCorps.Task.update_changeset/2`, which calls `changeset/2` and additionally sets the value of `task_updated_at` to the current timestamp
- modify `CodeCorpsWeb.TaskController.update/2` so it calls `Task.update_changeset/2` instead of `Task.changeset/2`
- probably make `Task.changeset/2` private, if no other piece of the code is using it
- modify `Task.changeset/2` tests so they are actually `Task.update_changeset/2` tests and add an assertion for the `task_updated_at` field being set, **if the changeset was made private**
- if the changeset **was not made private**, add `Task.update_changeset/2` tests in addition to the existing tests
- modify `Task.create_changeset/2` tests by adding an assertion for the `task_created_at` field

- **this is a good merge point**. The rest can be done separately

- modify `CodeCorps.GitHub.Event.Issues.ChangesetBuilder.build_changeset/3` to set both `task_updated_at` and `task_inserted_at` fields to their equivalent values in the github  payload
- add test assertions for `build_changeset/3` verifying that this is the case.

**Comment by begedin** [comment]
This has branched off into two separate issues. Once those are closed, we can close this as well

- [ ] #887 
- [ ] #888

**Comment by joshsmith** [comment]
Closing this in favor of the two separate issues.
