### ISSUE TITLE
Modify Task timestamps to accommodate github sync

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#888]
- Tasks can be multi-sourced. They can either by created or modified from Code Corps or GitHub (and in the future from other integrations, too).
- We will add a `created_at` and `modified_at` timestamp to `Task`.
  - `created_at` refers to the timestamp it was created _on the source that created it_. This is not simply when our API received it or when it wrote to the database.
  - `modified_at` refers to the timestamp it was modified _on the source that modified it_.
  - Whenever we're doing an update, *last write wins*.
- We will add a `created_from` and `modified_from` field that can be either `github` or `code_corps` for now. This tracks the original source of the creation or modification event.

**Comment by joshsmith** [comment]
@begedin cc @landongrindheim 

We had discussed in another issue the possibility of making a `GitHubIssue` relationship for a task. I wonder, in the context of this issue, if this obviates the need for aspects of the issue as described. (Sorry @landongrindheim – this development came up as an idea in the last 24).

The idea is that we would use this relationship to track some of the data about the issue on GitHub more specifically, including an `origin` field that indicates whether it was created on GitHub or created on Code Corps. This field _probably_ makes more sense to have on the `Task` itself since it would allow us to determine what to display in the UI: do we wait to load the timestamp until the `GitHubIssue` relationship has fully resolved, e.g.?

This may also _not_ obviate the need for any of this and simply increases the scope of our work. For example, the task cards UI does need to show time-ago timestamps. It would be preferable to have those timestamps load on first render with the actual time the task was created. Waiting for the `filter` endpoint of `/github-issues` to resolve would just complicate that UI. That does mean complicating things behind the scenes in the API and duplicating data, but at some obvious benefit to the user.

This could use some discussion and I'd love any thoughts anyone has to share, whether I called you out or not!

**Comment by joshsmith** [comment]
@begedin @landongrindheim could use thoughts here.

If we want to add an `origin` field, this should probably become a separate issue.

**Comment by landongrindheim** [comment]
@JoshSmith Can't say I fully grok the domain. I've mostly been doing refactorings guided by tests. Pretty great that that's possible 😄 . It sounds like the data model isn't locked down yet, so I would personally hold off on tying the Task model to a specific origin implementation.

That said, #960 should probably be closed and revisited when the data model has been settled on

**Comment by joshsmith** [comment]
Okay, after some discussion, I think what we've landed on is the following:

- Tasks and comments can be multi-sourced. They can either by created or modified from Code Corps or GitHub (and in the future from other integrations, too).
- We will add a `created_at` and `modified_at` timestamp to `Task` and `Comment`.
  - `created_at` refers to the timestamp it was created _on the source that created it_. This is not simply when our API received it or when it wrote to the database.
  - `modified_at` refers to the timestamp it was modified _on the source that modified it_.
  - Whenever we're doing an update, *last write wins*.
- We will add a `created_from` and `modified_from` field that can be either `github` or `code_corps` for now. This tracks the original source of the creation or modification event.
