### ISSUE TITLE
TaskSyncer.sync_all can return error changesets that get swallowed by our GitHub issues event handler without error

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#940]
# Problem

Quoting https://github.com/code-corps/code-corps-api/pull/805#issuecomment-329641688

>I got an `opened` event for `issues` (created by a GH user that had no corresponding user on CC) that resulted in no issue being created, a 200 returned, a `processed` status, and no user created on CC. That means the flow is broken and it's not clear where it's breaking down.

We need to go through such a process and verify that it goes through correctly and a user is actually created.

**Comment by joshsmith** [comment]
This is due to a bug in `GitHub.Event.Issues`. Inside the `do_handle/1` we do the following:

```elixir
    case Repo.transaction(multi) do
      {:ok, %{tasks: tasks}} -> {:ok, tasks} # This is our bug
      {:error, :repo, :unmatched_project, _steps} -> {:ok, []}
      {:error, _errored_step, error_response, _steps} -> {:error, error_response}
    end
```

The `{:ok, %{tasks: tasks}}` also happily pattern matches against tasks that `TaskSyncer.sync_all` returns regardless of whether `tasks` might be a `List` of, for example, `Ecto.Changeset`s with errors.

> A side note: I think `sync_all` implies things it does not, i.e. that we're syncing all the tasks for a given user and project's GitHub repos.

In this case, the bug is triggered _specifically_ by the markdown from GitHub being blank (it can be! so we found _two_ bugs here). Thus `do_handle` returns:

```elixir
{:ok,
 [#Ecto.Changeset<action: :insert,
   changes: %{github_issue_number: 13, github_repo_id: 17, project_id: 1,
     task_list_id: 1, title: "Another test account without a Code Corps user",
     user_id: 68},
   errors: [markdown: {"can't be blank", [validation: :required]},
    body: {"can't be blank", [validation: :required]}], data: #CodeCorps.Task<>,
   valid?: false>]}
```

My best guess is that we do not, in fact, want `sync_all` to return `{:ok, list(Task.t)}` in the event that one of these tasks has an error changeset. Probably the responsibility lies squarely there to:

- perhaps return an `error` tuple of some sort with some reasoning
- perhaps perform some logging (with some context)
- perhaps explicitly raise an error (with some context)

...or some combination of the above.

I don't yet know the exact implementation details or best patterns for handling something like this that's done in an enumerated way and then aggregated. Perhaps we could consider doing the `commit` step in the aggregate and failing when a changeset with errors are returned; see `sync/3` – I'm thinking really somewhere between the `build_changeset` and `commit` steps, with `commit` moving to `aggregate` somehow as a batch operation to the database via Ecto. Just my initial thoughts.

Stepping through this was pretty painful since I didn't know quite how far down the rabbit hole this went. We should really consider opening an issue to start doing some more explicit logging, especially for things that are so asynchronous like this.

**Comment by joshsmith** [comment]
One possible approach here is to rewrite our syncing fns to take in a `multi` so that we get the benefits of multi fns that accept a `changeset`. This may prove difficult, though (I've been trying this approach without much success) in the way we're iterating currently with `Enum.map` over `project_github_repos`. We still wanted to get the actual `tasks` back out at the end of the operation, and not just another `multi`. Still, it's possible this is the approach we want.

**Comment by joshsmith** [comment]
Another approach would be to do tail recursion of some sort on the `sync` step and return the first `{:error, %Ecto.Changeset{}}` that comes up, and rewriting `sync_all` to be a `with` with an `else` clause, so we only call `aggregate` when we've not yet encountered an error changeset.

**Comment by begedin** [comment]
@JoshSmith I'm really not sure what the best solution here, but it seems that the goal is, validate against all tasks at once, somehow, and don't swallow `{:error, changeset}` responses. This can certainly be solved, even with something as simple as, in aggregate result, if any of the individual responses are an `{:error, anything}`, return a tuple starting with `{:error, }`. That will make the whole step fail, and the transaction fail.

However, another issue is, if the github markdown is nil and our own cannot be nil, how do we deal with that anyway? Maybe we should consider allowing the markdown to be nil in this case.

I mean, a task with just a title **can** be useful and informative.

Edit: I see you've created #962 for this, so I guess we agree.

Really, the simplest solution here, if we want to go with "if one task fails, they all fail" is to return an `{:error, something}` if there's any changeset error in any of the individual updates. If that happens, the transaction will roll back.

**Comment by begedin** [comment]
There are also `Repo.insert_all/update_all/insert_or_update` macros, which we could potentially use to avoid having aggregates, but I would need to look into these much deeper.

**Comment by joshsmith** [comment]
Have not identified how yet, but it looks like #963 did not fix the issue here. Not sure if there are other individual changeset errors being swallowed. Will need to step through this once more to debug.

**Comment by joshsmith** [comment]
The comment directly above is a bit outdated as we fixed the markdown problem; think best approach now is tail recursion approach outlined above.
