### ISSUE TITLE
When creating a user from GitHub, also create their username

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#946]
# Problem

For setting a default username, we could:

- first see if their github username is available on CC
  - if yes, give them that username
  - if no, prefix with `github-`

We would need to increase our username validator limit to 46 chars in that case.

I'm not sure what other alternatives we could go for. Any ideas?

**Comment by begedin** [comment]
Looking at the code we have

- we allow setting a username upon registration
- we do not allow setting a username through any update endpoint (neither `update_changest` nor `changeset` cast that field.
- we sign in via email, not username
- i don't think it's common to allow a user to sign in via an external account username anyway, if their user record has been created via oatuh with an external account

Considering those (I'm not sure about the last one), we should

- Fix our flow to allow setting a username, and consider allow signing in via username. This is unrelated to github, really, but the parameter for the token endpoint is `username` and we use it as `email`, so at the very list, that's a very misleading piece of code.

- once we add github sign-in/sign-up, we should consider how we handle a lack of a local username

- For the use case of displaying a task or a comment, it should be enough to have the user view fall back on username to `%{github_username} (via GitHub)` or something like that, since the only place we'll be seeing it is in a task thread/ on the task list. We could even go further and do this purely on the client, as long as our user view on the API renders the `github_username` field in addition to the username field.

Generally, I don't like the idea of picking a username for our user ourselves, especially with something like a `github-` prefix, and even more so considering they currently cannot change it. This is more of a presentational issue.

**Comment by joshsmith** [comment]
For the `%{github_username} (via GitHub)` to work we would need to know that the comment/task originated on GitHub (i.e. the context) to know which fallback strategy to use (GitHub).

**Comment by joshsmith** [comment]
We should consider closing this issue and opening a new issue that keeps track of the context of the task/comment for us to know what to display @begedin.

**Comment by joshsmith** [comment]
We actually don't need the context to do this. What we do need is to keep track of whether a user created from GitHub's API is now a full user. If not, then we'll show `GitHub user @username` (for example) instead of the `@username`.

**Comment by joshsmith** [comment]
We may not even need what I wrote above, but it would certainly be nice to have something that indisputably tells us how to consider displaying a user: are they a CC user, a GH user, some other user, etc? Not sure a good naming convention here.

**Comment by joshsmith** [comment]
This is addressed, in part, by https://github.com/code-corps/code-corps-ember/pull/1379

**Comment by begedin** [comment]
@JoshSmith I'm not sure more needs to be addressed here. I wouldn't say the task itself needs additional context. The task author is what's important, or, to be more accurate, if we want the task to also display as "created on GitHub", then that would definitely be an issue separate from this one, as you said. 

Really, what we need to make sure is that the `UserView` renders the `:github_username` field, which it does.

We also need to make sure that the `:github_username` field is being set, which also seems to be the case. 

With that in mind, I don't think we need to do anything else here, for now, other than possibly opening the related issue. - #954

**Comment by joshsmith** [comment]
Closing this now since it seems irrelevant.
