### ISSUE TITLE
RFC: Do tasks and comments created from github need a github context?

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#954]
# Problem

As it is right now, task and comments which also exist on github should contain enough information for us to, for example, indicate this in the Ember app. 

By that, I mean, we have enough information to show a simple indicator along the lines of "this task/comment also exists in the associated github repo".

For the task specifically, we also have enough information to render the associated github repo information i the task sidebar.

What we don't have is

- Enough information to show a link to the task/comment. We could possibly compute the information we have to build the link, but the Github API documentation emphasizes we should prefer to use the prebuilt links their endpoints provide.
- Enough information to know for sure that the task/comment *originates* from github, meaning, it was created there and was then synced to codecorps, not the other way around. In some cases, we could safely conclude that, but not in all cases.

This Issue should serve as a place to discuss these things.

The question is

- Would information like that be useful. The answer is probably yes, but then it's a matter of what our priorities are.
- How would we approach storing that information

# Problem:  How to store context

- Adding an `origin` field, with the values `"github"` or `"codecorps"` would be simplest, but would not provide us with all the possibilities listed above
- Adding fields  to the task/comment would be most straightforward, but would grow the models in complexity
- Adding a relationship to a `GithubIssue`/`GithubComment` would probably be an improvement over that
- It may be enough to just have the view fetch the information from the API at render time, in some cases, but I don't really like that, just listing it as an option.
- It may be something that the client would be able to do in an asynchronous manner. We would just provide the basic information the client needs, in order to fetch more. Presumably,  not all of our potential future clients would need this info.

**Comment by joshsmith** [comment]
Yes, this information would be useful:

- Link to the GitHub task/comment
- Origin of the task/comment

I like the approach of the relationship to a `GitHubIssue` and `GitHubComment`, especially since we may add, e.g. Gitlab support in the future.

I definitely dislike the approach of fetching information from the API at render. This sounds like an `n+1` query nightmare.

Also, since I raised in an issue elsewhere the idea of being able to do this asynchronously in the future, the relationship approach makes increasingly more sense. You could have a relationship to an issue that is not yet created on GitHub, for example, and is in a `pending` status until the issue gets created on their API. This could then work similar to how GitHub treats their statuses UI for PRs. An issue sync could be in progress and the user on CC would be aware of it accordingly.

**Comment by joshsmith** [comment]
@begedin what's the relevance of this issue now?

**Comment by begedin** [comment]
@joshsmith I'll close this.

The basic requirements causing this issue to exist have been fulfilled with

```elixir
# in models/task.ex

field :created_from, :string, default: "code_corps"
field :modified_from, :string, default: "code_corps"

# ...

belongs_to :github_issue, CodeCorps.GithubIssue
belongs_to :github_repo, CodeCorps.GithubRepo
```

And really, it's live now. 

If we end up needing more, that will become apparent as people use it. For now, there is nothing else to do.
