### ISSUE TITLE
GitHub email overwrites user's email upon connecting

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-api#980]
# Problem

When the GitHub account connection process occurs (via `/oauth/github`), the user's email gets overwritten by the `GitHub.Adapters.User.from_github_user/1` function.

We should not be overwriting a user-provided email with an automatically provided one.

We need to identify if there are other places the GitHub user adapter is overwriting the user's email unexpectedly.

**Comment by begedin** [comment]
I believe the adapter is not the culprit here, since it's purpose is to translate the data from github to something we can use.

The problem should be resolved at the changeset level instead.

In fact, I would go as far as removing the behavior from the adapter where the email does not get translated just because it's nil. That's validation behavior to.

**Comment by joshsmith** [comment]
We should write a separate issue for this, likely:

> In fact, I would go as far as removing the behavior from the adapter where the email does not get translated just because it's nil. That's validation behavior to.
